name: CI/CD Pipeline
on:
  push: 
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Build Docker image
        run: docker build -t training_session .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Tag and push Docker image
        run: |
          docker tag training_session ${{ secrets.DOCKERHUB_USERNAME }}/training_session:v1.0
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/training_session:v1.0
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'trainingAppp'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .

